[package]
name = "tch-utils-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "2.0.16"
quote = "1.0.27"
darling = "0.20.1"
proc-macro2 = "1.0.58"