name: Rust Doc

on:
  push:
    branches: [ "main" ]
    paths: 
    - src/**
    - Cargo.toml
  pull_request:
    branches: [ "main" ]
    paths: 
    - src/**
    - Cargo.toml

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Doc
      run: cargo doc --verbose
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/doc
        branch: docs
    
